---
title: "Documenting Metrics Code in Oracle 12 databases"
author: "Andrea Brice"
date: "Tuesday, May 05, 2015"
---


Because of the quantity of metrics created across a variety of nodes, trying to manage the change in code even using a "GitHub" like system became problematic.  The problem of keeping the code up to date without human intervention becomes more imperative as multiple views can be changed several times during the introduction of new technology changes.  Manual updating is inherently structured for failure because of time constraints, "forgetfulness," or even just losing track of where code might be residing on a person's machine.

The standard of writing code in Oracle views was the easiest way of tracking what code is production for metrics which needed to be accessed by various internal workgroups for reporting.  View code could be copied, queried, between production & non-production schema by users with the proper authority.  Non-production views could be written under a non-production owner and then migrated into the production owner's schema as part of a conscious integration.

By leveraging the use of System Tables in both Oracle, and SQL Server databases, I was able to automate the process of updating the metrics database with the most recent code.  Even though code is changed multiple times a day, the last instance of change is what needed to be captured.  This last instance of the View code is available in System tables found in Oracle, SQL Server, and Teradata.  

The system table structures break up the object from the object name and the text.  The text is stored in an Oracle system table which hadn't been 

The steps
- delete the old data in database1
- update the table in database1 with new ddl dates & sql
- execute stored procedure dbo.SP_DR_VIEW_DEFINITIONS
- delete from dbo.DR_SQL_LIBRARY_UPLOAD_RESULT
- import of SQL LIBRARY RESULT data into table dbo.DR_SQL_LIBRARY_UPLOAD_RESULT
- execute stored procedure dbo.SP_DR_SQL_LIBRARY_FINAL
- select records of interest from table dbo.DR_SQL_LIBRARY_FINAL and insert into table dbo.DR_SQL_BULK_UPLOAD_TEMPLATE
          for output





SYS.ALL_DEPENDENCIES
SYS.ALL_OBJECTS 
SYS.VIEW$




create a table

create table schema.VIEW_LIST
(
DUMPDATE    DATE,
OBJECT_ID    NUMBER,
OWNER    VARCHAR2(10),
OBJECT_NAME    VARCHAR2(50),
OBJECT_TYPE    VARCHAR2(50),
CREATED    DATE,
STATUS    VARCHAR2(25),
LAST_DDL_TIME    DATE,
COLUMN_CT    NUMBER,
TEXTLENGTH    NUMBER,
TEXT    CLOB

) tablespace tablespace_name


















INSERT INTO VIEW_LIST

     select
        trunc(sysdate) as dumpdate,
        a.object_id,
        owner,
        object_name,
        object_type,
        created,
        status,
        last_ddl_time,
        cols as column_ct,
        TEXTLENGTH, to_lob(TEXT) as text
    
    from SYS.ALL_OBJECTS a, SYS.VIEW$ b
    
    where a.object_id = b.obj#
        and owner like '%3651'
        and object_name not in ('Insert_Name1_Here', 'Name2', 'Name3')
        
with
latestdate as (select max(dumpdate) as latest_dumpdate from VIEW_LIST)
       
SELECT 
    dumpdate
    object_id,
    owner||'.'||object_name as unique_id,
    owner,
        object_name,
        object_type,
        created,
        status,
        last_ddl_time,
        column_ct,
        TEXTLENGTH, 
        text
    

FROM VIEW_LIST, latestdate

WHERE DUMPDATE = latest_dumpdate;

